In [8]:
import pandas as pd
df = pd.read_csv('taiwan.csv')
df

     國家          日期     總確診數  新增確診數  新增死亡數
0    台灣  2020-01-16        0      0      0
1    台灣  2020-01-17        0      0      0
2    台灣  2020-01-18        0      0      0
3    台灣  2020-01-19        0      0      0
4    台灣  2020-01-20        0      0      0
..   ..         ...      ...    ...    ...
898  台灣  2022-07-02  3837856  34807     96
899  台灣  2022-07-03  3870528  32672     88
900  台灣  2022-07-04  3893643  23115     69
901  台灣  2022-07-05  3929627  35984    103
902  台灣  2022-07-06  3964188  34561     95

[903 rows x 5 columns]

In [10]:
df[["日期","總確診數"]]

             日期     總確診數
0    2020-01-16        0
1    2020-01-17        0
2    2020-01-18        0
3    2020-01-19        0
4    2020-01-20        0
..          ...      ...
898  2022-07-02  3837856
899  2022-07-03  3870528
900  2022-07-04  3893643
901  2022-07-05  3929627
902  2022-07-06  3964188

[903 rows x 2 columns]

In [12]:
df.iloc[:5]
df.loc[[0,1,2,3,4]]

   國家          日期  總確診數  新增確診數  新增死亡數
0  台灣  2020-01-16     0      0      0
1  台灣  2020-01-17     0      0      0
2  台灣  2020-01-18     0      0      0
3  台灣  2020-01-19     0      0      0
4  台灣  2020-01-20     0      0      0